### PR TITLE
Mainly Frontend Stuff and some Backend Integration

### PR DESCRIPTION
**Pull request by ssasukek**
A set of updates mainly focusing on improving and adjustment to the frontend and backend.
For the Frontend updates:
- added digital clock component and better user interface
- enabled timezone selection via dropdown
- updated login and registration pages to connect to backend
- creating a reset pass pages for user
Backend updates:
- integrated the backend functionality for tasks, list and users
- implement password reset features
- connecting to database

### CODE REVIEW

**Comment by stkeopila** [comment]
Is Everything Good Here? Everything looks good to me.

**Comment by abel-alcala** [comment]
im not sure whats causing the push to fail for the static webpage, my last commits didnt touch the frontend specifically

**Comment by ssasukek** [comment]
> im not sure whats causing the push to fail for the static webpage, my last commits didnt touch the frontend specifically

**Comment by ssasukek** [comment]
maybe check with the deployment workflow or dependencies. it could be due to some error when building.

**Pull request closed without merging**
